language: python
python:
- '2.7'
install: pip install -r requirements.txt
script: python -m unittest discover
notifications:
  slack:
    secure: cwT08Q1ualqm/3urOpQvDx5U0AixYlYXLtlT7/ePusGmj6Zhu0y+ZGELck6YlkM4SRSrNAvrYFwlJPQeAGP3q9tRSYiKxI2uMEe9cK2KZU7T0ARwlR7HwkRkJ2XOiUsoWH3XQqsqqQK43UrGpD0/iZ0NTPVo99attNiF06gsD5g1uyJns9YV9XN5wVUg7iDJUne2I+ATa5L4r5cBpsxL90Ce8tVYVC/yjKNz9zBoRyeyNzG+ILutvb8ovny7+NCPVkl27BieHHgzgpplHJChaSB5XJKKzek0sbgJGvQrLZX/1pXDuWQZpBZcaqiNYzZEYRLY2BVpx27hwl9PKNhWVwEoWq7AE1mx15MnmYKXOUEhkJWaQ7KztYRuTJL46/xLVKLzr2nQddG9/PcBhjMBobeDsG0gQqoBYeYfTbVdmQUP9XXcrZihWAlIt1apWXOuD7SqskIYcT501z9/0Wnf7ahqeOybTOEWSps75Aj8tArKr4wIrp6ML5QpTqKDqMVR0aku8dChmIJXOyY1f7wP0uH2x0vOepGjlYkD4xI1S5OKpiooyNhug4Og8R/YJcXXEtFJfRcyTAp53zAJabiscxxWWqQpM1OYMuYd11nptiRvzlboEUNszaZTQvA32uylRZ8PvRb0VwGRkLic4XrW0WUOy4NLltOyJCVhujiF/u0=
